### ISSUE TITLE
Dedupe Committee Names

### ISSUE THREAD

**Issue by billdybas** [rit-sse/OneRepoToRuleThemAll#195]
I thought this had been fixed, but on scoreboard when adding a membership, the committee names are not deduplicated, so there's multiple "General" committees.

**Comment by akath20** [comment]
I think this is in the database vs. a programming error. I am hesitant to delete them from the database without more research if there will be issues references those duped rows id's.

**Comment by billdybas** [comment]
Are there actual duplicate “General” committees? At the time, I think I thought that because each primary belongs to the General committee, somewhere when we fetch committees from officers, we don’t account that there may be multiple officers per committee?

**Comment by gavrielrh** [comment]
I've put a bandaid fix on this one for the moment, the cause is sequelize scoping via includes and the one-to-one relationship being confused as there are multiple officers in the general committee.

The bandaid fix: updating the relationship from hasOne to hasMany (committee->officer) in the node-api.
One additional issue with the include scoping is that the fields of the included model get tacked onto the base model. I've remedied this in a not so great way by forcing sequelize to not include these attributes from the included model, but I'd love to find a better way.
