### ISSUE TITLE
Scoreboard New Member Bug

### ISSUE THREAD

**Issue by laura-king** [rit-sse/OneRepoToRuleThemAll#207]
When adding a membership for a new member(someone not autofilling) it does not appear to be actually adding the membership in. However, the autofill does work after that so it's probably adding the person to the db.

**Comment by wadeanthony0100** [comment]
Probably relevant 422 error:

`{"error":"insert or update on table \"memberships\" violates foreign key constraint \"memberships_userDce_fkey\""}`

**Comment by billdybas** [comment]
That error is from [here](
https://github.com/rit-sse/node-api/blob/a9a90fd42540dd10ecfa074b130bc95d2c5be351/routes/memberships.js#L51). Make sure in the form, we create a user if they don’t already exist and we include the dce in the create membership request. Sounds like it might be missing.

**Comment by wadeanthony0100** [comment]
So I've been doing some investigating, just wanted to dump what I think I know here...

I'm not sure exactly what's happening here...

```JS
export function addMembership(user, membership) {
    return (dispatch, getState, { Users, Memberships }) => {
      dispatch(loading(ADD_MEMBERSHIP));
      return Users.update(user.dce, user)
        .then(Memberships.create(membership))
        .then(member => dispatch(createAction(ADD_MEMBERSHIP, member, `Membership added for ${user.dce}`)))
        .catch(err => dispatch(createAction(ADD_MEMBERSHIP, err)));
    };
  }
```

I would expect `Users.update` to do a `PUT` to create a user (undocumented but looking at node-api this is how a user is expected to be made), wait for it to come back, then `Users.create` would make a `POST` to memberships to create the associated membership. It looks like this order of operations isn't being respected by the client.

Resending the `POST` request from the console succeeded, so I feel like this may be our root cause (last image).

The browser appears to be making these requests in parallel:
<img width="1440" alt="screen shot 2018-09-04 at 3 19 44 pm" src="https://user-images.githubusercontent.com/7254185/45054262-728a1f80-b05a-11e8-96cd-3fba60a25b6c.png">

Looks like userDce is being included in the `POST` request:
<img width="569" alt="screen shot 2018-09-04 at 3 56 22 pm" src="https://user-images.githubusercontent.com/7254185/45054557-58047600-b05b-11e8-8f11-78cf7f702d8d.png">

Resending a request after the dust settles yeilds success:
<img width="850" alt="screen shot 2018-09-04 at 4 48 45 pm" src="https://user-images.githubusercontent.com/7254185/45057022-8043a300-b062-11e8-80b0-e000267c4d23.png">

**Comment by wadeanthony0100** [comment]
Another thing to notice is that, even when `Memberships.create` returned a `422`, the page showed a success toast (or whatever the banner is), and not an error message- Should we not `throw` when we get back a 400 or 500?

**Comment by billdybas** [comment]
`Users.update` uses the API client [`update`](https://github.com/rit-sse/api-client/blob/6f5139286cdfd6eeab3b124b17b0e81cc3522bb1/src/api.js#L82) for users.

I think your fix is correct. Because `Memberships.create()` is not wrapped in a function, it's immediately executed, so based on network speeds / request order, sometimes we get a concurrency bug. We would try to create a Membership for a User that doesn't exist yet.

Notice the only [other place](https://github.com/rit-sse/OneRepoToRuleThemAll/blob/219870b16400c29bdfaede8b5da61be4bcc6e681/app/js/officers/actions.js#L35) where we do this double request thing is wrapped in a function.

Regarding the error handling, I think the issue is that we're not handling errors on the `Memberships.create()` calls because it's at a different level than the `.catch()`.

I think it would need to change to:
```js
export function addMembership(user, membership) {
  return (dispatch, getState, { Users, Memberships }) => {
    dispatch(loading(ADD_MEMBERSHIP));
    return Users.update(user.dce, user)
      .then(() => Memberships.create(membership)
        .catch(err => dispatch(createAction(ADD_MEMBERSHIP, err)))) // <-- this
      .then(member => dispatch(createAction(ADD_MEMBERSHIP, member, `Membership added for ${user.dce}`)))
      .catch(err => dispatch(createAction(ADD_MEMBERSHIP, err)));
  };
}
```

Alternatively, if we have `async/await` support in this repo (didn't check; not sure), you could do:
```js
export function addMembership(user, membership) {
  return async (dispatch, getState, { Users, Memberships }) => {
    dispatch(loading(ADD_MEMBERSHIP));
    try {
      const member = await Users.update(user.dce, user);
      await Memberships.create(membership);
      dispatch(createAction(ADD_MEMBERSHIP, member, `Membership added for ${user.dce}`));
    } catch (err) {
      dispatch(createAction(ADD_MEMBERSHIP, err));
    }
  }
}
```
which IMO is much easier to understand at a glance.
