### ISSUE TITLE
Page for consolidated social media links

### ISSUE THREAD

**Issue by lbokun** [rit-sse/OneRepoToRuleThemAll#210]
I think it'd be cool to have an additional page with links to our different social media pages and accounts, along with short descriptions for what they're used for. Specifically, we have a Facebook page and a Facebook group, so clarifying the difference between those would be helpful.

**Comment by billdybas** [comment]
We actually do have a page w/ our social media links at https://sse.rit.edu/social. 

We should make it more discoverable since it's only linked at the bottom of the "About" page. I'd suggest adding a link to it on the navbar ["About" dropdown menu](https://github.com/rit-sse/OneRepoToRuleThemAll/blob/053d78d593af8df8a19279f98565253694ab6cfd/app/js/common/components/SSENav.jsx#L54).

The social page is auto-generated from [this markdown file](https://github.com/rit-sse/OneRepoToRuleThemAll/blob/devlop/app/markdown/social.md). Feel free to submit a PR with useful descriptions about each link. And maybe you could separate which links we actively use vs. old social accounts. There's an open PR w/ some additional social links – #199.

**Comment by akath20** [comment]
Closed by https://github.com/rit-sse/OneRepoToRuleThemAll/commit/8658c2282802240656bcebb193f4d6e29bd95d0b
