### ISSUE TITLE
Download Events Button requires page reload to initiate download. 

### ISSUE THREAD

**Issue by akath20** [rit-sse/OneRepoToRuleThemAll#224]
The calendar icon at /events goes to https://sse.rit.edu/api/v2/events.ics, but it says page not found. Once the page is refreshed, then the download starts. It shouldn't require an additional refresh.

**Comment by billdybas** [comment]
I know what the issue is here:

You used a `<Link>` component [there](https://github.com/rit-sse/OneRepoToRuleThemAll/blob/a2f30ce1406868872f5e69224cd14bd1699af82d/app/js/events/Page.jsx#L28). Those components are from React Router and should only be used to navigate to pages within the app. What's happening is React Router is looking for a route to match to `/api/v2/events.ics` but can't find one – so it shows the not found page. When you refresh the page, traefik picks up that you're visiting an `/api/v2` route and sends your request to the API which initiates the download.

I think if you change it to an `<a>` tag it should be fine. Might need to add `target="_blank" rel="noopener"`
