### ISSUE TITLE
No redirect from http://sse.se.rit.edu

### ISSUE THREAD

**Issue by derekerdmann** [rit-sse/OneRepoToRuleThemAll#61]
http://sse.se.rit.edu is the old SSE website URL that most companies and alumni would already know. Everything under that domain (including email, ideally) should redirect to the sse.rit.edu version.

**Comment by vuzDylan** [comment]
@7imbrook Did we break this with this new deploy or has this been broken for a while now?

**Comment by kristenmills** [comment]
I noticed it maybe a week ago for the first time. Could be broken for longer than that though.

**Comment by kristenmills** [comment]
@vuzDylan @7imbrook Also email should still just work unless Kurt changed something, right?

**Comment by 7imbrook** [comment]
Emails still works, sse.se still points who knows where.

**Comment by billdybas** [comment]
In the Fall, we contacted ITS to update _one_ of our DNS records and they meddled w/ __all__ of our DNS records, and it seems like a bunch broke.

The DNS and MX records for `sse.se.rit.edu` have not existed for several months now.

Right now, the correct (and only) way of accessing the SSE's website is at [`https://sse.rit.edu`](https://sse.rit.edu).
And, the correct (and only) way of sending email to one of the [SSE officers](https://sse.rit.edu/officers) is through their `@sse.rit.edu` email.

Since the old way has been broken for several months, I'm going to assume that anyone who needed to contact the SSE at the old address would have realized they're broken, as trying to access the website would have given them a "This site can't be reached" page and trying to access by email would have given them a bounceback email indicating undeliverable. They would have likely [searched for the SSE](https://www.google.com/search?q=society+of+software+engineers) and would have found our actual site & officers' emails. (Not to be confused with the [Milwaukee School of Engineering Society of Software Engineers](http://msoe-sse.com/))

As a result, I'm not going to worry about adding in a redirect or mail forwarding. If I notice any old links on any of our GitHub projects or other websites (like the [RITpedia](https://ritpedia.rit.edu/Society_of_Software_Engineers) or [SE Dept](http://www.se.rit.edu/society-software-engineers)), I'll be sure to update them to the current format.

**Comment by billdybas** [comment]
Looks like we also have a page on the [RocWiki](https://rocwiki.org/Rochester_Institute_of_Technology/Society_of_Software_Engineers)
